services:

  postgresql-master:
    image: docker.io/bitnami/postgresql:latest
    ports:
      - "5432:5432"
    volumes:
      - "postgresql_master_data:/bitnami/postgresql"
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=mysecretpassword
      - POSTGRESQL_DATABASE=my_database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d my_database"]
      interval: 2s
      timeout: 2s
      retries: 30

  postgresql-slave:
    image: docker.io/bitnami/postgresql:latest
    ports:
      - "5433:5432"
    depends_on:
      postgresql-master:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=host.docker.internal
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_PASSWORD=mysecretpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d my_database"]
      interval: 2s
      timeout: 2s
      retries: 30

volumes:
  postgresql_master_data:
    driver: local